# Generated by Django 4.2.7 on 2023-12-19 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("age", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.IntegerField(
                        max_length=10,
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999)
                        ],
                    ),
                ),
                ("mail_id", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("COMPUTER SCIENCE", "COMPUTER SCIENCE"),
                            ("ART", "ART"),
                            ("SOCIAL SCIENCE", "SOCIAL SCIENCE"),
                            ("MEDICAL", "MEDICAL"),
                            ("COMMERCE", "COMMERCE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "courses",
                    models.CharField(
                        choices=[
                            ("AI", "AI"),
                            ("BA ART", "BA ART"),
                            ("MBBS", "MBBS"),
                            ("LLB", "LLB"),
                            ("B.COM", "B.COM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("Order Placed", "Order Placed")], max_length=50
                    ),
                ),
                ("materials", models.CharField(max_length=50)),
            ],
        ),
    ]
